//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteConsumeWCF.ServiceWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWCF.IServiceClient")]
    public interface IServiceClient {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClient/Perkalian", ReplyAction="http://tempuri.org/IServiceClient/PerkalianResponse")]
        decimal Perkalian(decimal angkaPertama, decimal angkaKedua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClient/Perkalian", ReplyAction="http://tempuri.org/IServiceClient/PerkalianResponse")]
        System.Threading.Tasks.Task<decimal> PerkalianAsync(decimal angkaPertama, decimal angkaKedua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClient/Pembagian", ReplyAction="http://tempuri.org/IServiceClient/PembagianResponse")]
        decimal Pembagian(decimal angkaPertama, decimal angkaKedua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClient/Pembagian", ReplyAction="http://tempuri.org/IServiceClient/PembagianResponse")]
        System.Threading.Tasks.Task<decimal> PembagianAsync(decimal angkaPertama, decimal angkaKedua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClient/Penjumlahan", ReplyAction="http://tempuri.org/IServiceClient/PenjumlahanResponse")]
        decimal Penjumlahan(decimal angkaPertama, decimal angkaKedua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClient/Penjumlahan", ReplyAction="http://tempuri.org/IServiceClient/PenjumlahanResponse")]
        System.Threading.Tasks.Task<decimal> PenjumlahanAsync(decimal angkaPertama, decimal angkaKedua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClient/Pengurangan", ReplyAction="http://tempuri.org/IServiceClient/PenguranganResponse")]
        decimal Pengurangan(decimal angkaPertama, decimal angkaKedua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClient/Pengurangan", ReplyAction="http://tempuri.org/IServiceClient/PenguranganResponse")]
        System.Threading.Tasks.Task<decimal> PenguranganAsync(decimal angkaPertama, decimal angkaKedua);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceClientChannel : SiteConsumeWCF.ServiceWCF.IServiceClient, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClientClient : System.ServiceModel.ClientBase<SiteConsumeWCF.ServiceWCF.IServiceClient>, SiteConsumeWCF.ServiceWCF.IServiceClient {
        
        public ServiceClientClient() {
        }
        
        public ServiceClientClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClientClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal Perkalian(decimal angkaPertama, decimal angkaKedua) {
            return base.Channel.Perkalian(angkaPertama, angkaKedua);
        }
        
        public System.Threading.Tasks.Task<decimal> PerkalianAsync(decimal angkaPertama, decimal angkaKedua) {
            return base.Channel.PerkalianAsync(angkaPertama, angkaKedua);
        }
        
        public decimal Pembagian(decimal angkaPertama, decimal angkaKedua) {
            return base.Channel.Pembagian(angkaPertama, angkaKedua);
        }
        
        public System.Threading.Tasks.Task<decimal> PembagianAsync(decimal angkaPertama, decimal angkaKedua) {
            return base.Channel.PembagianAsync(angkaPertama, angkaKedua);
        }
        
        public decimal Penjumlahan(decimal angkaPertama, decimal angkaKedua) {
            return base.Channel.Penjumlahan(angkaPertama, angkaKedua);
        }
        
        public System.Threading.Tasks.Task<decimal> PenjumlahanAsync(decimal angkaPertama, decimal angkaKedua) {
            return base.Channel.PenjumlahanAsync(angkaPertama, angkaKedua);
        }
        
        public decimal Pengurangan(decimal angkaPertama, decimal angkaKedua) {
            return base.Channel.Pengurangan(angkaPertama, angkaKedua);
        }
        
        public System.Threading.Tasks.Task<decimal> PenguranganAsync(decimal angkaPertama, decimal angkaKedua) {
            return base.Channel.PenguranganAsync(angkaPertama, angkaKedua);
        }
    }
}
